name: Deploy to Wasmer Edge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Wasmer CLI
        run: curl https://get.wasmer.io -sSfL | sh

      - name: Add Wasmer to PATH
        run: echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Deploy to Wasmer Edge
        env:
          WASMER_TOKEN: ${{ secrets.WASMER_TOKEN }}
        run: wasmer deploy --non-interactive
